* Building a Modern Computer from First Principles

#+BEGIN_QUOTE
The cognitive ability to “divide and conquer” a complex system into manageable modules is empowered by yet another cognitive gift: our ability to discern between the abstraction and the implementation of each module. In computer science, we take these words concretely: abstraction describes what the module does, and implementation describes how it does it. With this distinction in mind, here is the most important rule in system engineering: when using a module as a building block—any module—you are to focus exclusively on the module’s abstraction, ignoring completely its implementation details.
#+END_QUOTE

** Hardware

*** Boolean Logic

#+BEGIN_QUOTE
The use of Boolean algebra for analyzing the abstract behavior of logic gates was articulated in 1937 by Claude Shannon, leading to what is sometimes described as the most important M.Sc. thesis in computer science. (p. 38)
#+END_QUOTE

| Operator | Math         | Formal     |
|----------+--------------+------------|
| And      | x \cdot y    | x \wedge y |
| Or       | x + y        | x \vee y   |
| Not      | \overline{x} | \neg x     |

**** Not
If (in) out = 0, else out = 1
\neg in
***** Source :tangle projects/01/Not.hdl:


**** Everything from NAND
Read appendix 1.
**** Table2Expr
Read appendix 1.
